### ISSUE TITLE
請問zero-shot-actions如何使用"其他"的資料集在tfvaegan

### ISSUE THREAD

**Issue by hungtsosung** [e96031413/tfvaegan#1]
Hi 你好,
我有在原有作者Akshitac 的問答集上看到您的詢問相同的問題, 而此問題也是困擾我許久, 可否請教您?
1. 如何更改為其他的Dataset? 具體的作法為何?
2. i3D 及Splits檔案詳細內容為何, 及如何製作?
3. 在att_splits.mat 中的資料*_loc 例如test_seen_loc, 內容是什麼?

Sincerely,
洪佐松
新竹NTHU

**Comment by e96031413** [comment]
@hungtsosung 
您好：

* 如何更改為其他的Dataset? 具體的作法為何?

我的作法可以參考我在[這篇文章](https://yanwei-liu.medium.com/image-feature-extraction-from-resnet101-with-pytorch-ade6b1dfcc3a)所寫的[程式碼](https://gist.github.com/e96031413/2f4cb8f730e39eafec6cde6323f096ca#file-mat_feature_extract_with_pytorch_gpu_resnet101-py)

簡單來說就是先進行Feature extraction後將這些特徵保存到mat檔案裡面

* i3D 及Splits檔案詳細內容為何, 及如何製作?

檔案可以透過Octave(或是Matlab軟體)開啟來看，製作方面我並不確定，但是我推測可以考慮使用python的某個套件將資料進行切割後，寫入到mat檔案裡面
```
> load fileName.mat
```
* 在att_splits.mat 中的資料*_loc 例如test_seen_loc, 內容是什麼?

![1](https://user-images.githubusercontent.com/30921855/127279594-28496ce3-8519-4ea1-8499-a695c84a0c4e.JPG)

由於我沒嘗試過Zero-shot-actions的部份，所以可能沒辦法幫上太大的忙，以上是我針對一般zero-shot圖片分類所測試出來的方式

**Comment by hungtsosung** [comment]
非常感謝你的建議及作法, 我先試一下更改Dataset , 至於如何建立action 的i3D 及att_splits 我也寫信問一下原著作.
再次謝謝您:)
